### ISSUE TITLE
As developer, I need to create the remaining UIs, so that I can integrate those UIs to our backend services.

### ISSUE THREAD

**Issue by ricardobrg** [mytiki/platform-mon-storefront#104]
### Acceptance Criteria

Static UIs are created and can be accessed in the storefront site.

### Tasks

- [x] #109 
- [x] #111 
- [x] #112 
- [x] #113 
- [x] #114 
- [x] #115 
- [x] #116 
- [x] #117

### Relates to

Continuation of #59

**Comment by MiroBenicio** [comment]
closed as completed
