### ISSUE TITLE
Plan and Create the API Spec

### ISSUE THREAD

**Issue by MiroBenicio** [mytiki/platform-mon-storefront#31]
### Reason

Plan the Integration with the API

### Description

We should review and analyze the current shape of the UI and create an API Spec to the data it needs.

### Success Criteria

- [ ] API Spec of the current project

**Comment by ricardobrg** [comment]
The focus of this task is to create the JSONs for the Dataset and My Account screens:
- Dataset:
  - Name and description 
     <img width="751" alt="Captura de Tela 2024-04-29 às 08 03 22" src="https://github.com/mytiki/platform-mon-storefront/assets/8357343/7c789a72-2e8e-42df-bce8-51ebb666a393">
  
  - Metadata: <br/>
     <img width="345" alt="Captura de Tela 2024-04-29 às 08 04 57" src="https://github.com/mytiki/platform-mon-storefront/assets/8357343/aa3e83a6-92f1-4c13-9ae6-dd2cd1608ca6">
  
  - Menu: list of available datasets
     <img width="291" alt="Captura de Tela 2024-04-29 às 08 01 48" src="https://github.com/mytiki/platform-mon-storefront/assets/8357343/7f5629de-975a-484e-9148-65b532978f72">

  - charts:
     Charts that should be displayed with the respective chart.js configuration
     

  - Taxonomy
     List of fields name, type and description 
     <img width="354" alt="Captura de Tela 2024-04-29 às 08 09 10" src="https://github.com/mytiki/platform-mon-storefront/assets/8357343/61cf8c5c-e483-450b-8a7b-34b2c2b06706">

**Comment by ricardobrg** [comment]
My Account

- Menu: list of available datasets   
- A list of data sources objects with:
   - date
   - approved (y/n) 
   - agreement link
   - number of records
   This data will fuel the tables in the main content and in the sidebar
   
    <img width="247" alt="Captura de Tela 2024-04-29 às 08 19 33" src="https://github.com/mytiki/platform-mon-storefront/assets/8357343/5c09505a-8fa9-4e3b-8c85-71ace3ea705e">
    
    <img width="266" alt="Captura de Tela 2024-04-29 às 08 19 27" src="https://github.com/mytiki/platform-mon-storefront/assets/8357343/8cf2668e-3aff-4abe-9508-60de04d1dee5">

- Chart data for "data sources" and "approved for" (just the chart data, not chart.js config, since the chart designs are default.)
    <img width="257" alt="Captura de Tela 2024-04-29 às 08 20 14" src="https://github.com/mytiki/platform-mon-storefront/assets/8357343/37c32eb8-0792-4bdb-8eb8-9710a394f1a0">

**Comment by ricardobrg** [comment]
@MiroBenicio please create the issues to implement these JSONs as data sources. 
- It should be obtained from a `fetch` on page load in the frontend. 
- Define the types and placeholders/examples. 
- Add tests and documentation. 
- add the issues in the 0.0.2 milestone

close this after the issues are ready
