### ISSUE TITLE
Implement JSONs for dataset and legal compliance screen

### ISSUE THREAD

**Issue by MiroBenicio** [mytiki/platform-mon-storefront#53]
### User Story

#48

### Description

As a engineer, we should implement the JSONs described in #31 to make to start the implementation of the API spec.

### Acceptance Criteria

- [x] a JSON/fetch for the dataset screen
- [ ] a JSON/fetch for the dataset menu list
- [ ] a JSON/fetch for the legal compliance screen
- [ ] types and placeholders for each one

**Comment by ricardobrg** [comment]
data set screen types open api spec:

components:
  schemas:
    Stats:
      type: object
      properties:
        updates:
          type: string
          enum: ['DAILY', 'WEEKLY', 'MONTHLY']
        updated_at:
          type: string
          format: date-time
        years:
          type: string
        contains:
          type: array
          items:
            type: string
        approved_for:
          type: array
          items:
            type: string
    ChartData:
      type: array
      items:
        type: object
        properties:
          width:
            type: integer
          height:
            type: integer
          type:
            type: string
            enum: ['bar', 'line']
          labels:
            type: array
            items:
              type: string
          datasets:
            type: array
            items:
              type: object
              properties:
                label:
                  type: string
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      x:
                        type: number
                      y:
                        type: number
                borderColor:
                  type: string
                backgroundColor:
                  type: string
                fill:
                  type: boolean

**Comment by ricardobrg** [comment]
DatasetRoute:
      type: object
      properties:
        type:
          type: string
        route:
          type: string
        subtitle:
          type: string
