### ISSUE TITLE
As a developer, I want to verify which screens can be done using strapi and which needs designs, so that I can finish the prototype 

### ISSUE THREAD

**Issue by MiroBenicio** [mytiki/platform-mon-storefront#59]
### Acceptance Criteria

Identify which screens can be deployed using the CMS and which needs to be created

### Tasks

- [x] #60 
- [x] #61 
- [x] #62 
- [x] #63
- [x] #64
- [x] #65
- [x] #66
- [x] #67
- [x] #68
- [x] #69

**Comment by ricardobrg** [comment]
@mike-audi please flag which will just be content from the CMS and which will need specific design

**Comment by ricardobrg** [comment]
Needs specific design:
#60 and #61

The others are ready to be done. I will close this issue and create new stories for these tasks
