### ISSUE TITLE
Design Organization Screen

### ISSUE THREAD

**Issue by MiroBenicio** [mytiki/platform-mon-storefront#60]
### User Story

#59

### Description

We should design the organization screen

<img width="830" alt="Captura de Tela 2024-05-03 às 10 32 16" src="https://github.com/mytiki/platform-mon-storefront/assets/96149507/1297f36d-285d-467f-a2a8-381e9ea69281">

**Comment by ricardobrg** [comment]
This screen will be created in the client dashboard
