### ISSUE TITLE
Design Billing and Usage Screen

### ISSUE THREAD

**Issue by MiroBenicio** [mytiki/platform-mon-storefront#61]
### User Story

#59

### Description

We should design the Billing and Usage 

<img width="857" alt="Captura de Tela 2024-05-03 às 10 36 33" src="https://github.com/mytiki/platform-mon-storefront/assets/96149507/ab4ae530-f4ab-4486-9952-744a89c8460b">

**Comment by ricardobrg** [comment]
This screen will be part of the client dashboard
